name: Independent Android Desktop Container

on:
  workflow_dispatch:

jobs:
  android-runner:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Enable KVM
        run: |
          sudo ls -l /dev/kvm
          sudo usermod -aG kvm $USER

      - name: Start Redroid Container
        run: |
          docker run -d --rm --privileged \
            --name redroid-1 \
            -p 5555:5555 \
            redroid/redroid:11.0.0-latest \
            androidboot.hardware=mt6833 ro.secure=0 ro.debuggable=1
        
      - name: Setup Environment, ADB and Tunnel
        run: |
          sudo apt-get update
          sudo apt-get install -y android-tools-adb scrcpy ffmpeg
          
          # Bore tünel aracını indir (Dışarıdan kendi bilgisayarından ADB ile bağlanmak istersen diye)
          curl -sLO https://github.com/ekzhang/bore/releases/download/v0.5.1/bore-v0.5.1-x86_64-unknown-linux-musl.tar.gz
          tar -xzf bore-v0.5.1-x86_64-unknown-linux-musl.tar.gz
          chmod +x bore
          
          echo "=========================================="
          echo "DIŞ BAĞLANTI İÇİN ADB ADRESİNİZ:"
          echo "=========================================="
          ./bore local 5555 --to bore.pub &
          
          # Konteynerin ve tünelin açık kalması (30 dakika)
          sleep 1800
